{{- if .Values.networkPolicy.enabled }}
---
# NetworkPolicy for Server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "clearflask.server.fullname" . }}
  labels:
    {{- include "clearflask.server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "clearflask.server.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    # Allow from connect pods
    - from:
        - podSelector:
            matchLabels:
              {{- include "clearflask.connect.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
    # Allow from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # Allow to MySQL
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: mysql
      ports:
        - protocol: TCP
          port: 3306
    # Allow to LocalStack
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: localstack
      ports:
        - protocol: TCP
          port: 4566
    # Allow to ElasticSearch
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: elasticsearch
      ports:
        - protocol: TCP
          port: 9200
    # Allow external HTTPS and DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
---
# NetworkPolicy for Connect
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "clearflask.connect.fullname" . }}
  labels:
    {{- include "clearflask.connect.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "clearflask.connect.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    # Allow from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 9080
        - protocol: TCP
          port: 9443
  egress:
    # Allow to server
    - to:
        - podSelector:
            matchLabels:
              {{- include "clearflask.server.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
    # Allow external HTTPS and DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}
