{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearflask-dependencies.mysql.fullname" . }}
  labels:
    {{- include "clearflask-dependencies.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
{{- end }}
