apiVersion: v2
name: clearflask-dependencies
description: Optional infrastructure dependencies for ClearFlask (MySQL, LocalStack, ElasticSearch)
type: application
version: 0.1.0
appVersion: "1.0"
home: https://clearflask.com
sources:
  - https://github.com/clearflask/clearflask
keywords:
  - clearflask
  - mysql
  - localstack
  - elasticsearch
  - dynamodb
  - s3
maintainers:
  - name: Matus Faro
    email: matus@smotana.com
