{{- if .Values.server.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clearflask.server.serviceAccountName" . }}
  labels:
    {{- include "clearflask.server.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.connect.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clearflask.connect.serviceAccountName" . }}
  labels:
    {{- include "clearflask.connect.labels" . | nindent 4 }}
  {{- with .Values.connect.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
